# app/config/security.yml

security:
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext
    OCUserBundle\Entity\User: plaintext

  role_hierarchy:
    ROLE_GERANT: ROLE_USER
    ROLE_ADMIN: [ROLE_USER, ROLE_GERANT]
    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
    main:
                entity:
                    class:    OCUserBundle\Entity\User
                    property: username

  firewalls:
      dev:
        pattern: ^/(_(profiler|wdt)|css|images|js)/
        security: false

      main:
            pattern:      ^/
            anonymous:    true
            provider:     main
            form_login:
              login_path: login
              check_path: login_check
            logout:
              path:       logout
              target:     /

  access_control:

    #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }